FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia el archivo BackendLibreria.csproj y restaura las dependencias
COPY Backend/BackendLibreria/BackendLibreria/BackendLibreria.csproj Backend/BackendLibreria/
RUN dotnet restore Backend/BackendLibreria/BackendLibreria.csproj

# Copia el resto del código
COPY . .

# Cambia al directorio del proyecto y publica
WORKDIR /src/Backend/BackendLibreria
RUN dotnet publish BackendLibreria.csproj -c Release -o /app/out -p:AssemblyName=BackendLibreriaApp

# Imagen final
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .

ENV ASPNETCORE_URLS=http://0.0.0.0:${PORT}
EXPOSE 8080

ENTRYPOINT ["dotnet", "BackendLibreriaApp.dll"]
